# Site settings
title: Portfolio
author: "Yevgenii Dimoglo"
description: Personal gamedev portfolio
lang: "jp"
future: true

show_downloads: false
theme: jekyll-theme-architect

# Layout
show_social: false
show_excerpts: false
show_frame: true

# Menu
navigation:
  - {file: "index_en.md", title: "Home", icon: home}
  - {file: "README.md", title: "About Me", icon: adress-card}
